apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-simple-app
  labels:
    app: nginx-simple-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-simple-app
  template:
    metadata:
      labels:
        app: nginx-simple-app
    spec:
      containers:
      - name: nginx
        image: <YOUR_ARTIFACT_REGISTRY_IMAGE>   # will be replaced in pipeline
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-simple-app-svc
spec:
  type: LoadBalancer
  selector:
    app: nginx-simple-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
