# ==========================================
# 1. Deployment (unchanged)
# ==========================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-simple-app
  labels:
    app.kubernetes.io/name: nginx-simple-app
    app.kubernetes.io/part-of: nginx-simple-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-simple-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-simple-app
    spec:
      containers:
        - name: nginx
          image: us-docker.pkg.dev/hot-cold-drp/gke-docker-repo/nginx-simple-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

---
# ==========================================
# 2. Service (GKE external LoadBalancer)
# ==========================================
apiVersion: v1
kind: Service
metadata:
  name: nginx-simple-app-svc
  labels:
    app.kubernetes.io/name: nginx-simple-app
  # For INTERNAL LB instead, uncomment the annotation below and add an RFC1918 subnet:
  # annotations:
  #   cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: nginx-simple-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
