# ==========================================
# 1. Deployment (same as yours)
# ==========================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-simple-app
  labels:
    app.kubernetes.io/name: nginx-simple-app
    app.kubernetes.io/part-of: nginx-simple-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-simple-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-simple-app
    spec:
      containers:
        - name: nginx
          image: us-docker.pkg.dev/hot-cold-drp/gke-docker-repo/nginx-simple-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

---
# ==========================================
# 2. BackendConfig (enables Cloud CDN)
# ==========================================
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: nginx-cdn-backendconfig
spec:
  cdn:
    enabled: true
  connectionDraining:
    drainingTimeoutSec: 0

---
# ==========================================
# 3. Service (change LoadBalancer → NodePort)
# ==========================================
apiVersion: v1
kind: Service
metadata:
  name: nginx-simple-app-svc
  labels:
    app.kubernetes.io/name: nginx-simple-app
  annotations:
    cloud.google.com/backend-config: '{"default":"nginx-cdn-backendconfig"}'
    cloud.google.com/neg: '{"ingress": true}'   # <-- REQUIRED
spec:
  # Use NodePort (or omit 'type' for ClusterIP). DO NOT use LoadBalancer here.
  type: NodePort
  selector:
    app.kubernetes.io/name: nginx-simple-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      # optional: nodePort: 31061

      # optional: nodePort: 31061

---
# ==========================================
# 4. Ingress (creates Global LB + Cloud CDN)
# ==========================================
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-cdn-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    # Optional: reserve static IP first, then reference it here:
    # kubernetes.io/ingress.global-static-ip-name: "nginx-cdn-ip"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-simple-app-svc
            port:
              number: 80