name: Deploy GKE Nginx App

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  LOCATION: us-central1
  CLUSTER_NAME: app-cluster-hot
  IMAGE_NAME: us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gke-docker-repo/nginx-simple-app:latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v4

      # 2️⃣ Authenticate to GCP
      - name: Google Cloud Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 3️⃣ Set GCP project
      - name: Set GCP project
        run: gcloud config set project $PROJECT_ID

      # 4️⃣ Configure Docker for Artifact Registry
      - name: Configure Docker
        run: gcloud auth configure-docker us-docker.pkg.dev --quiet

      # 5️⃣ Build Docker image
      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME .

      # 6️⃣ Push Docker image to Artifact Registry
      - name: Push Docker Image
        run: docker push $IMAGE_NAME

      # 7️⃣ Get GKE credentials
      - name: Get GKE Credentials
        run: gcloud container clusters get-credentials $CLUSTER_NAME --region $LOCATION --project $PROJECT_ID

      # 8️⃣ Update Kubernetes deployment with new image
      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s-app-deployment.yaml
          kubectl set image deployment/nginx-simple-app nginx=$IMAGE_NAME
          kubectl rollout status deployment/nginx-simple-app
