name: Terraform Plan & Apply

on:
   workflow_dispatch:
     
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main

permissions:
  contents: read
  id-token: write
  pull-requests: write

env:
  TF_IN_AUTOMATION: "true"
  WORKING_DIR: root
  TFVARS_PATH: ../env/dev/terraform.tfvars

jobs:
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}
    outputs:
      has_changes: ${{ steps.plan.outputs.has_changes }}
    steps:
      - uses: actions/checkout@v4
      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init -reconfigure
      - run: terraform validate

      - name: Terraform Plan (fail fast; detect changes)
        id: plan
        run: |
          set -o pipefail
          terraform plan \
            -var-file="${{ env.TFVARS_PATH }}" \
            -input=false -no-color -out=tfplan.bin -detailed-exitcode | tee plan.txt
          code=$?
          if [ $code -eq 0 ]; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          elif [ $code -eq 2 ]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "Plan failed. See plan.txt above."
            exit $code
          fi

      - name: Upload Plan Artifact (only if changes)
        if: ${{ steps.plan.outputs.has_changes == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: |
            ${{ env.WORKING_DIR }}/tfplan.bin
            ${{ env.WORKING_DIR }}/plan.txt

  apply:
    needs: plan
    # ⬇️ Apply only if it's a push to main AND plan had changes
    if: ${{ needs.plan.outputs.has_changes == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    environment: prod
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}
    steps:
      - uses: actions/checkout@v4

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan           # ⬅️ no repository/run-id
          path: ${{ env.WORKING_DIR }}

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: hashicorp/setup-terraform@v3
      - run: terraform init -reconfigure
      - run: terraform apply -input=false -auto-approve tfplan.bin


